// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7CT0_8_IENsJrCzUWkmd1g8RMcUzyYmY',
    appId: '1:825250749124:android:721cb5ab745db555090791',
    messagingSenderId: '825250749124',
    projectId: 'happily-ever-after-4b2fe',
    databaseURL:
        'https://happily-ever-after-4b2fe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'happily-ever-after-4b2fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn3a67V0b5dprJPc3zVmhefotNmvN6i7U',
    appId: '1:825250749124:ios:129f3cd75a15aed3090791',
    messagingSenderId: '825250749124',
    projectId: 'happily-ever-after-4b2fe',
    databaseURL:
        'https://happily-ever-after-4b2fe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'happily-ever-after-4b2fe.appspot.com',
    androidClientId:
        '825250749124-s45chj8kjdteihdls432j0qiv3j8n0te.apps.googleusercontent.com',
    iosClientId:
        '825250749124-8qchmst7ihvrpaq041bavbebm465l7qc.apps.googleusercontent.com',
    iosBundleId: 'care.hea.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn3a67V0b5dprJPc3zVmhefotNmvN6i7U',
    appId: '1:825250749124:ios:129f3cd75a15aed3090791',
    messagingSenderId: '825250749124',
    projectId: 'happily-ever-after-4b2fe',
    databaseURL:
        'https://happily-ever-after-4b2fe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'happily-ever-after-4b2fe.appspot.com',
    androidClientId:
        '825250749124-s45chj8kjdteihdls432j0qiv3j8n0te.apps.googleusercontent.com',
    iosClientId:
        '825250749124-8qchmst7ihvrpaq041bavbebm465l7qc.apps.googleusercontent.com',
    iosBundleId: 'care.hea.app',
  );
}
