// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8AUKbFk8EdKqib45kT73VVV6eZoK45y0',
    appId: '1:825250749124:web:b981e1efe5bf26ba090791',
    messagingSenderId: '825250749124',
    projectId: 'happily-ever-after-4b2fe',
    authDomain: 'happily-ever-after-4b2fe.firebaseapp.com',
    databaseURL:
        'https://happily-ever-after-4b2fe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'happily-ever-after-4b2fe.appspot.com',
    measurementId: 'G-H713K1J5C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7CT0_8_IENsJrCzUWkmd1g8RMcUzyYmY',
    appId: '1:825250749124:android:721cb5ab745db555090791',
    messagingSenderId: '825250749124',
    projectId: 'happily-ever-after-4b2fe',
    databaseURL:
        'https://happily-ever-after-4b2fe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'happily-ever-after-4b2fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn3a67V0b5dprJPc3zVmhefotNmvN6i7U',
    appId: '1:825250749124:ios:129f3cd75a15aed3090791',
    messagingSenderId: '825250749124',
    projectId: 'happily-ever-after-4b2fe',
    databaseURL:
        'https://happily-ever-after-4b2fe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'happily-ever-after-4b2fe.appspot.com',
    androidClientId:
        '825250749124-ivrc77aqemm47m1ltdigeg2c4on135fe.apps.googleusercontent.com',
    iosClientId:
        '825250749124-8qchmst7ihvrpaq041bavbebm465l7qc.apps.googleusercontent.com',
    iosBundleId: 'care.hea.app',
  );
}
