// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFsz1fh3cNb946fV0-f6zGLFckSh0RLzY',
    appId: '1:639499003234:web:dd9a9cfae35a7f84fcf83b',
    messagingSenderId: '639499003234',
    projectId: 'happily-ever-after-dev',
    authDomain: 'happily-ever-after-dev.firebaseapp.com',
    storageBucket: 'happily-ever-after-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtvJp2eQGr93OWwxrpqO3GxvchRPSUvBU',
    appId: '1:639499003234:android:a58c2b8d849d7103fcf83b',
    messagingSenderId: '639499003234',
    projectId: 'happily-ever-after-dev',
    storageBucket: 'happily-ever-after-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-EJkPD8f4fQ9gT_xPYKnZ_1PsK5kXtCg',
    appId: '1:639499003234:ios:a6e144e7af2c356dfcf83b',
    messagingSenderId: '639499003234',
    projectId: 'happily-ever-after-dev',
    storageBucket: 'happily-ever-after-dev.appspot.com',
    iosClientId: '639499003234-ksub7617j7dk07k0i9dmi5u67pv8tukc.apps.googleusercontent.com',
    iosBundleId: 'health.happilyeverafter.app',
  );
}
