version: '3.8'

services:
    hea_backend:
        build:
            context: .
            target: development
        command: npm run start:debug
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=thisisasupersecurepassword
            - JWT_SECRET=thisisasupersecurejwtsecret
        ports:
            - 3000:3000
            - 9229:9229
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules

    db:
        image: postgis/postgis
        restart: always
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=thisisasupersecurepassword
        ports:
          - 5432:5432

    adminer:
        image: adminer
        restart: always
        ports:
        - 5433:8080
