version: '3.8'

services:
    hea_backend:
        build:
            context: .
            target: development
        command: npm run start:debug
        ports:
            - 3000:3000
            - 9229:9229
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules