name: experiment_dart_commonjs_module
description: Experimenting with CommonJS modules written in Dart
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  js: ^0.6.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
  # JavaScript builds
  build: ^2.3.0
  build_runner: ^2.1.11
  build_web_compilers: ^3.2.3
  node_preamble: ^2.0.1
