import '../../widgets/page.dart';
import 'ch01_introduction.dart';
import 'ch02_now.dart';
import 'ch03_goals.dart';
import 'ch04_rhythm.dart';
import 'ch05_owning.dart';
import 'ch06_routine.dart';
import 'ch07_diary.dart';
import 'ch09_done.dart';

Lesson sleep = Lesson([
  PageDef(IntroductionWelcome, () => IntroductionWelcome()),
  PageDef(IntroductionGettingToKnowYou, () => IntroductionGettingToKnowYou()),
  PageDef(IntroductionHowTrackHealth, () => IntroductionHowTrackHealth()),
  PageDef(IntroductionHowTrackSleep, () => IntroductionHowTrackSleep()),
  PageDef(IntroductionHowTrackSleep2, () => IntroductionHowTrackSleep2()),
  PageDef(NowFirstThingsFirst, () => NowFirstThingsFirst()),
  PageDef(NowTimeGoneBed, () => NowTimeGoneBed()),
  PageDef(NowMinutesFallAsleep, () => NowMinutesFallAsleep()),
  PageDef(NowTimeOutBed, () => NowTimeOutBed()),
  PageDef(NowGetSleep, () => NowGetSleep()),
  PageDef(NowHowEfficientSleep, () => NowHowEfficientSleep()),
  PageDef(NowDifficultySleeping, () => NowDifficultySleeping()),
  PageDef(NowSleepDisturbances, () => NowSleepDisturbances()),
  PageDef(NowTroubleSleepingWakeUp, () => NowTroubleSleepingWakeUp()),
  PageDef(NowTroubleSleepingBathroom, () => NowTroubleSleepingBathroom()),
  PageDef(NowTroubleSleepingBreath, () => NowTroubleSleepingBreath()),
  PageDef(NowTroubleSleepingSnore, () => NowTroubleSleepingSnore()),
  PageDef(NowTroubleSleepingCold, () => NowTroubleSleepingCold()),
  PageDef(NowTroubleSleepingHot, () => NowTroubleSleepingHot()),
  PageDef(NowTroubleSleepingBadDreams, () => NowTroubleSleepingBadDreams()),
  PageDef(NowTroubleSleepingPain, () => NowTroubleSleepingPain()),
  PageDef(NowOtherFactors, () => NowOtherFactors()),
  PageDef(NowOverallQuality, () => NowOverallQuality()),
  PageDef(NowSleepMedication, () => NowSleepMedication()),
  PageDef(NowFatigue, () => NowFatigue()),
  PageDef(NowEnthusiasm, () => NowEnthusiasm()),
  PageDef(NowScore, () => NowScore()),
  PageDef(GoalsSetting, () => GoalsSetting()),
  PageDef(GoalsTimeToSleep, () => GoalsTimeToSleep()),
  PageDef(GoalsDoingBeforeBed, () => GoalsDoingBeforeBed()),
  PageDef(GoalsEmbraceAndManifest, () => GoalsEmbraceAndManifest()),
  PageDef(GoalsGettingThere, () => GoalsGettingThere()),
  PageDef(RhythmConsistency, () => RhythmConsistency()),
  PageDef(RhythmWhy, () => RhythmWhy()),
  PageDef(RhythmHow, () => RhythmHow()),
  PageDef(RhythmPeaksAndDips1, () => RhythmPeaksAndDips1()),
  PageDef(RhythmPeaksAndDips2, () => RhythmPeaksAndDips2()),
  PageDef(RhythmSettingCourseIntro, () => RhythmSettingCourseIntro()),
  PageDef(RhythmSettingCourse, () => RhythmSettingCourse()),
  PageDef(OwningRoutine, () => OwningRoutine()),
  PageDef(OwningZeitgebers, () => OwningZeitgebers()),
  PageDef(OwningRoutineActivities1, () => OwningRoutineActivities1()),
  PageDef(OwningRoutineActivities2, () => OwningRoutineActivities2()),
  PageDef(OwningRoutineActivities3, () => OwningRoutineActivities3()),
  PageDef(OwningTheDayNegative, () => OwningTheDayNegative()),
  PageDef(RoutineBeforeBedtime, () => RoutineBeforeBedtime()),
  PageDef(RoutineIntro, () => RoutineIntro()),
  PageDef(RoutineActivities, () => RoutineActivities()),
  PageDef(RoutineCalmingActivitiesIntro, () => RoutineCalmingActivitiesIntro()),
  PageDef(RoutineCalmingActivities1, () => RoutineCalmingActivities1()),
  PageDef(RoutineCalmingActivities2, () => RoutineCalmingActivities2()),
  PageDef(RoutineCalmingActivities3, () => RoutineCalmingActivities3()),
  PageDef(RoutineReminders, () => RoutineReminders()),
  PageDef(RoutineOptInGroup, () => RoutineOptInGroup()),
  PageDef(RoutineGroupInstructions, () => RoutineGroupInstructions()),
  PageDef(RoutinePledgeIntro, () => RoutinePledgeIntro()),
  PageDef(RoutinePledge, () => RoutinePledge()),
  PageDef(DiaryReminders, () => DiaryReminders()),
  PageDef(DiaryRemindersTime, () => DiaryRemindersTime()),
  PageDef(DiaryStart, () => DiaryStart()),
  PageDef(Done, () => Done()),
  PageDef(DoneIncreased, () => DoneIncreased()),
  PageDef(DoneDecreased, () => DoneDecreased()),
  PageDef(DoneContinue, () => DoneContinue()),
  PageDef(DoneWithHealer, () => DoneWithHealer()),
  PageDef(DoneWithTeam, () => DoneWithTeam()),
  PageDef(DoneEnd, () => DoneEnd()),
]);
