name: app

on:
  push:

env:
  FLUTTER_VERSION: 2.10

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
      - uses: actions/checkout@v2
      - name: Set up problem matcher
        run: echo "::add-matcher::.github/matcher-flutter.json"
      - uses: actions/cache@v3
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-flutter-${{ hashFiles('hea/app/**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
      - run: flutter analyze app --no-fatal-infos
      - run: flutter format app --output none --set-exit-if-changed
