name: app

on:
  push:
    branches: [main]
    paths: ['app/**']
  pull_request:
    branches: [main]
    paths: ['app/**']

env:
  FLUTTER_VERSION: '3.0'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@9d48f4efd5460d7013af812069d08b23f37aed20
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      - uses: actions/checkout@v3
      - name: Set up problem matcher
        run: echo "::add-matcher::.github/matcher-flutter.json"
      - uses: actions/cache@v3
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-flutter-${{ hashFiles('app/**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
      - run: flutter pub get
        working-directory: app
      - run: flutter pub run build_runner build
        working-directory: app
      - run: flutter analyze app --no-fatal-infos | sed 's/^   info/warning/g'
      - run: flutter format app --output none --set-exit-if-changed

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@9d48f4efd5460d7013af812069d08b23f37aed20
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      - uses: actions/checkout@v3
      - name: Set up problem matcher
        run: echo "::add-matcher::.github/matcher-flutter.json"
      - uses: actions/cache@v3
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-flutter-${{ hashFiles('app/**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
      - run: flutter pub get
        working-directory: app
      - run: flutter pub run build_runner build
        working-directory: app
      - run: python tools/generate_full_coverage.py
        working-directory: app
      - run: flutter test --reporter expanded --coverage
        working-directory: app
      - name: Upload code coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: app/coverage/lcov*.info
          retention-days: 10
      - name: Comment code coverage (Pull request)
        uses: romeovs/lcov-reporter-action@dda1c9b1fa1622b225e9acd87a248751dbcc6ada
        with:
          lcov-file: app/coverage/lcov.info
          filter-changed-files: true
          delete-old-comments: true
        if: ${{ github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
      - name: Comment code coverage (Commit)
        uses: romeovs/lcov-reporter-action@dda1c9b1fa1622b225e9acd87a248751dbcc6ada
        with:
          lcov-file: app/coverage/lcov.info
          filter-changed-files: false
          delete-old-comments: false
        if: ${{ github.event_name == 'push' }}
# vim: set et ts=2 sw=2:
