name: backend
on: 
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    defaults:
      run:
        working-directory: ./backend
    
    steps:
      
      - name: Copy repository
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: npm ci
      
      - name: Lint check
        run: npm run ci-lint
      
      - name: Format check
        run: npm run ci-format

      - name: Build
        run: npm run build
      
      - name: Run tests
        run: npm run test