name: fastlane-beta

on:
  push:
    tags: ["v*"]

defaults:
  run:
    working-directory: hea/app
env:
  FLUTTER_VERSION: 2.10

jobs:
  ios:
    #runs-on: macos-latest
    runs-on: [self-hosted, macos-latest]
    outputs:
      deployment_id: ${{ steps.deployment.outputs.deployment_id }}
    steps:
      - name: Create deployment
        uses: chrnorm/deployment-action@9fea95f56f4cd87321ff4ec22dea1ffaaed2c902
        id: deployment
        with:
          token: "${{ github.token }}"
          environment: ios-beta
      - name: Update deployment status (in_progress)
        uses: chrnorm/deployment-status@15b9298912c2b84635561a68d35c84d43e3d6c94
        with:
          token: ${{ github.token }}
          state: in_progress
          target_url: ${{ github.server_url }}/${{ github.repository }}/runs/${{ github.run_id }}?check_suite_focus=true
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
      - uses: subosito/flutter-action@d8687e6979e8ef66d2b2970e2c92c1d8e801d7bf
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true
      - uses: actions/checkout@v2
        with:
          path: hea
      - uses: actions/cache@v3
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-flutter-${{ hashFiles('hea/app/**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
      - uses: actions/cache@v3
        with:
          path: hea/app/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('hea/app/**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - run: fastlane ios beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
      #- name: Upload IPA
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: ios
      #    path: hea/app/Runner.ipa
      #    retention-days: 30
      - name: Update deployment status (failure)
        uses: chrnorm/deployment-status@15b9298912c2b84635561a68d35c84d43e3d6c94
        with:
          token: ${{ github.token }}
          state: failure
          target_url: ${{ github.server_url }}/${{ github.repository }}/runs/${{ github.run_id }}?check_suite_focus=true
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
        if: ${{ failure() }}

  ios-distribute:
    runs-on: ubuntu-latest
    needs: [ios]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          path: hea
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
          working-directory: hea/app
      - run: bundle exec fastlane ios beta_distribute
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
      - name: Update deployment status (success)
        uses: chrnorm/deployment-status@15b9298912c2b84635561a68d35c84d43e3d6c94
        with:
          token: ${{ github.token }}
          state: success
          target_url: ${{ github.server_url }}/${{ github.repository }}/runs/${{ github.run_id }}?check_suite_focus=true
          deployment_id: ${{ needs.ios.outputs.deployment_id }}
      - name: Update deployment status (failure)
        uses: chrnorm/deployment-status@15b9298912c2b84635561a68d35c84d43e3d6c94
        with:
          token: ${{ github.token }}
          state: failure
          target_url: ${{ github.server_url }}/${{ github.repository }}/runs/${{ github.run_id }}?check_suite_focus=true
          deployment_id: ${{ needs.ios.outputs.deployment_id }}
        if: ${{ failure() }}

  android:
    runs-on: ubuntu-latest
    environment:
      name: android-beta
    env:
      CODE_SIGNING_REPO: ${{ github.workspace }}/code-signing
    steps:
      - uses: subosito/flutter-action@d8687e6979e8ef66d2b2970e2c92c1d8e801d7bf
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true
      - uses: actions/checkout@v2
        with:
          path: hea
      - uses: actions/cache@v3
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-flutter-${{ hashFiles('hea/app/**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
      - uses: actions/checkout@v2
        with:
          repository: happilyeveraftercorp/code-signing
          ssh-key: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
          path: code-signing
      - name: Configure keystore
        run: |
          echo "storeFile=${{ env.CODE_SIGNING_REPO }}/android/release.keystore" >> android/key.properties
          echo "keyAlias=hea" >> android/key.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
          working-directory: hea/app
      - run: bundle exec fastlane android beta
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.CODE_SIGNING_REPO }}/android/firebase-app-distribution.json
      #- name: Upload APK
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: android
      #    path: hea/app/build/app/outputs/flutter-apk/app-release.apk
      #    retention-days: 30
