name: format-code

on:
  push:
    branches: [main]
    paths: ['**.yaml', '**.yml', '**.md', '**.json', '**.hbs', '**.js', '**.py']
  pull_request:
    branches: [main]
    paths: ['**.yaml', '**.yml', '**.md', '**.json', '**.hbs', '**.js', '**.py']

jobs:
  misc:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Format yaml, md, json, hbs, js
        uses: actionsx/prettier@13639c769e72c3e51d53ae383b681a684c883233
        with:
          args: --config backend/package.json --write '**/*.yaml' '**/*.yml' '**/*.md' '**/*.json' '**/*.hbs' '**/*.js' '!app/fastlane/README.md'
      - name: Format app/tools
        working-directory: app/tools
        run: |
          pip install -r requirements.txt
          black .
      - name: Commit changes if any
        run: |
          git config user.name "GitHub Actions"
          git config user.email "action@github.com"
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git commit -m "style: Automatic code formatting" -a
            git push
          fi

# vim: set et ts=2 sw=2:
